source 'https://rubygems.org'

gem 'rack', '1.5.2'
gem 'bcrypt-ruby', '~> 3.0.1'
gem 'yard'

gem 'rake'
gem 'tilt', '~> 1.3.6'
gem 'rabl', '~> 0.8.4'
gem 'oj', '~> 2.0.12'
gem 'activesupport', '~> 3.2.13'

gem 'sass'
gem 'slim'

gem 'mongo'
gem 'mongoid', '~> 3.0.23'
gem 'dalli', '~> 2.6.3'

gem 'padrino', '0.11.1'
gem 'sinatra-synchrony', '~> 0.4.1'
gem 'thin', '~> 1.5.1'
gem 'capistrano'
gem 'rvm-capistrano'

gem 'pry'
gem 'pry-remote'
gem 'pry-nav'

gem 'rspec', group: 'test'
#gem 'spork', group: 'test'
gem 'capybara', group: 'test'
gem 'cucumber', group: 'test'
gem 'rack-test', require: 'rack/test', group: 'test'
#gem 'httparty'
gem 'jsonpath'
gem 'nokogiri'
gem 'cucumber-api-steps', group: 'test'
gem 'database_cleaner', group: 'test'
gem 'factory_girl', require: false, group: 'test'
gem 'guard', group: 'test'
gem 'guard-cucumber', group: 'test'
gem 'growl', group: 'test'