development:
 sessions:
   default:
     database: reactor2_development
     hosts:
       - localhost:27017
#     database: improva
#     hosts:
#       - ec2-54-244-82-4.us-west-2.compute.amazonaws.com:27017
#     username: improva
#     password: WXJP0q97MWliHn0dhQH9
   nsi:
     database: nsi
     hosts:
       - ec2-54-244-143-34.us-west-2.compute.amazonaws.com:27017

production:
 sessions:
   default:
     database: improva
     hosts:
       - localhost:27017
   nsi:
     database: nsi
     hosts:
       - localhost:27017

test:
 sessions:
   default:
     database: reactor2_test
     hosts:
       - localhost:27017
   nsi:
     database: reactor2_test_nsi
     hosts:
       - localhost:27017